/**
 * Pixel art icons generator - MS Paint / retro style.
 * Each icon is defined as a pixel grid and rendered to a data URI.
 */

const C = {
  _: null,           // transparent
  W: '#ffffff',      // white
  B: '#000000',      // black
  G: '#39ff14',      // green (accent)
  Y: '#ffcc00',      // yellow
  R: '#ff3333',      // red
  C: '#00d4ff',      // cyan
  D: '#666666',      // dark gray
  L: '#aaaaaa',      // light gray
  O: '#ff8800',      // orange
  P: '#cc88ff',      // purple
};

function renderIcon(grid, size = 16) {
  const h = grid.length;
  const w = grid[0].length;
  const canvas = document.createElement('canvas');
  canvas.width = w;
  canvas.height = h;
  const ctx = canvas.getContext('2d');

  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const color = grid[y][x];
      if (color) {
        ctx.fillStyle = color;
        ctx.fillRect(x, y, 1, 1);
      }
    }
  }
  return canvas.toDataURL();
}

function p(str) {
  // Parse a compact string into a color grid
  // Each char maps to a color
  const map = {
    '.': null, 'W': C.W, 'B': C.B, 'G': C.G, 'Y': C.Y,
    'R': C.R, 'C': C.C, 'D': C.D, 'L': C.L, 'O': C.O, 'P': C.P,
  };
  return str.trim().split('\n').map(row =>
    [...row.trim()].map(ch => map[ch] || null)
  );
}

// ---- TOOL ICONS (12x12 pixel art, MS Paint inspired) ----

export const ICON_PENCIL = renderIcon(p(`
..........BG
.........BYG
........BYB.
.......BYB..
......BYB...
.....BYB....
....BYB.....
...BWB......
..BWB.......
.BBB........
.B..........
............
`));

export const ICON_ERASER = renderIcon(p(`
............
..BBBBBBBB.
.BWWWWWWWWB
.BWWWWWWWWB
.BWWWWWWWWB
.BWLLLLLLWB
.BLLLLLLLWB
.BLLLLLLLLB
.BLLLLLLLLB
.BLLLLLLLLB
..BBBBBBBB.
............
`));

export const ICON_FILL = renderIcon(p(`
.....BB.....
....BYBB....
...BYYBB...
...BYYYB...
..BYYYYB...
..BYYYYB...
.BYYYYB....
.BYYYYB....
.BYYBB.....
..BBB......
...B.......
..BB.......
`));

export const ICON_EYEDROPPER = renderIcon(p(`
..........BB
.........BWB
........BWB.
.......BWB..
......BWB...
.....BWB....
....BWB.....
...BWB......
..BRB.......
.BRB........
.BB.........
............
`));

export const ICON_SELECT = renderIcon(p(`
BGBGBGBGBGBG
G..........B
B..........G
G..........B
B..........G
G..........B
B..........G
G..........B
B..........G
G..........B
B..........G
GBGBGBGBGBGB
`));

export const ICON_UNDO = renderIcon(p(`
............
....GGGG....
...G....G...
..G......G..
.G..........
GG..........
GGGGGG......
GG..........
.G..........
..G.........
...G........
............
`));

export const ICON_REDO = renderIcon(p(`
............
....GGGG....
...G....G...
..G......G..
..........G.
..........GG
......GGGGGG
..........GG
..........G.
.........G..
........G...
............
`));

export const ICON_GRID = renderIcon(p(`
GGGGGGGGGGGG
G...G...G..G
G...G...G..G
G...G...G..G
GGGGGGGGGGGG
G...G...G..G
G...G...G..G
GGGGGGGGGGGG
G...G...G..G
G...G...G..G
G...G...G..G
GGGGGGGGGGGG
`));

export const ICON_LAYERS = renderIcon(p(`
............
..GGGGGGGG..
.G........G.
.GGGGGGGGGG.
..G........G
..GGGGGGGGGG
...G.......G
...GGGGGGGGG
....G......G
....GGGGGGGG
............
............
`));

export const ICON_CLEAR = renderIcon(p(`
.BBB...BBB..
.BRRRRRRRB..
..BRRRRRRB..
..BRRRRRB...
...BRRRRB...
...BRRRB....
....BRRB....
....BRRB....
....BRRB....
...BRRRRB...
...BBBBBB...
............
`));

export const ICON_EXPORT = renderIcon(p(`
....GGGG....
....G..G....
....G..G....
..GGGGGGGG..
...GGGGGG...
....GGGG....
.....GG.....
............
GGGGGGGGGGGG
G..........G
G..........G
GGGGGGGGGGGG
`));

export const ICON_ONION = renderIcon(p(`
....PPPP....
..PP....PP..
.P........P.
.P..CCCC..P.
P..C....C..P
P..C....C..P
P..C....C..P
.P..CCCC..P.
.P........P.
..PP....PP..
....PPPP....
............
`));

export const ICON_PLAY = renderIcon(p(`
............
..GG........
..GGGG......
..GGGGGG....
..GGGGGGGG..
..GGGGGGGGGG
..GGGGGGGG..
..GGGGGG....
..GGGG......
..GG........
............
............
`));

export const ICON_STOP = renderIcon(p(`
............
.RRRRRRRRRR.
.RRRRRRRRRR.
.RRRRRRRRRR.
.RRRRRRRRRR.
.RRRRRRRRRR.
.RRRRRRRRRR.
.RRRRRRRRRR.
.RRRRRRRRRR.
.RRRRRRRRRR.
............
............
`));

// Symmetry icons
export const ICON_SYM_V = renderIcon(p(`
............
.....CC.....
.....CC.....
..G..CC..G..
..GG.CC.GG..
.GGG.CC.GGG
..GG.CC.GG..
..G..CC..G..
.....CC.....
.....CC.....
............
............
`));

export const ICON_SYM_H = renderIcon(p(`
............
....G..G....
...GG..GG...
..GGG..GGG..
............
CCCCCCCCCCCC
CCCCCCCCCCCC
............
..GGG..GGG..
...GG..GG...
....G..G....
............
`));

export const ICON_SYM_BOTH = renderIcon(p(`
............
.....CC.....
..G..CC..G..
..GG.CC.GG..
.....CC.....
CCCCCCCCCCCC
CCCCCCCCCCCC
.....CC.....
..GG.CC.GG..
..G..CC..G..
.....CC.....
............
`));

export const ICON_SYM_OFF = renderIcon(p(`
............
............
..DDDDDDDD..
..D......D..
..D......D..
..D......D..
..D......D..
..D......D..
..D......D..
..DDDDDDDD..
............
............
`));

export const ICON_LINE = renderIcon(p(`
............
.G..........
..GG........
...GG.......
....GG......
.....GG.....
......GG....
.......GG...
........GG..
.........GG.
..........G.
............
`));

export const ICON_SHAPE = renderIcon(p(`
GGGGGGGGGGGG
G..........G
G..........G
G..........G
G..........G
G..........G
G..........G
G..........G
G..........G
G..........G
G..........G
GGGGGGGGGGGG
`));

export const ICON_ELLIPSE = renderIcon(p(`
....GGGG....
..GG....GG..
.G........G.
G..........G
G..........G
G..........G
G..........G
G..........G
.G........G.
..GG....GG..
....GGGG....
............
`));

export const ICON_WAND = renderIcon(p(`
..........YY
.........YOY
........YOY.
.......YOY..
......YOY...
.....YYY....
....YCY.....
...YCY......
..YCY.......
.YCY........
YCY.........
YY..........
`));

export const ICON_PHOTO = renderIcon(p(`
GGGGGGGGGGGG
G..........G
G..........G
G..C.......G
G.CCC..D...G
G..C...DD..G
G......D.D.G
G.DDDDD..DG
GDD...DDDDDG
GD.........G
G..........G
GGGGGGGGGGGG
`));
